unique_ids:
  assets:
    standard-page.html: SLU7YIN6C7ZMQOVAYCMRLA542Z5LVNGT
    theme.css: EPTIPR47GYYULSBT7BKMA4KIZZXHLBKB
  forms:
    ThingsBoardInterface: AQ4CIUUQU3WJ3M7ZAGTKWITU2JZYHNNI
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1730540937165970287201376.9093'
